---
- name: Copy parameter files to app servers
  template:
    src: templates/aas20.j2 
    dest: "C:\\install\\AutomationParameters\\aas20.params"
    newline_sequence: '\r\n'

- name: Run AAS20
  win_shell: C:\SWPM\sapinst.exe SAPINST_INPUT_PARAMETERS_URL=C:\install\AutomationParameters\aas20.params SAPINST_EXECUTE_PRODUCT_ID=NW_DI:NW740SR2.MSS.PD SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  become: yes
  become_method: runas
  become_user: "{{ sap_install_user }}"
  vars:
    ansible_become_password: "{{ sap_install_password }}"