---
- hosts: data-crm, data-isu
  gather_facts: true
  any_errors_fatal: true

  vars_files:
    - "vars/windows.yaml"
    - "vars/local_vars.yaml"
  
  tasks: 

  - include_role:
      name: data_restore