---
- hosts: app-crm
  gather_facts: true
  any_errors_fatal: true

  vars:
        
  vars_files:
    - vars/windows.yaml
    - vars/local_vars.yaml

  tasks: 
  - include_role:
      name: sap_import_users
      tasks_from: sap_import_users